
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./component/Footer";
import Header from "./component/Header";

const urwdin = localFont({
  src: [
    {
      path: "../../public/font/urwdin/URWDIN-Regular.eot",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/urwdin/URWDIN-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/urwdin/URWDIN-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/urwdin/URWDIN-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-urwdin",
});

const stratum = localFont({
  src: [
    {
      path: "../../public/font/stratum/StratumNo1-Black.eot",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/stratum/StratumNo1-Black.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/stratum/StratumNo1-Black.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/stratum/StratumNo1-Black.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-stratum",
})
const stratumReg = localFont({
  src: [
    {
      path: "../../public/font/stratum/StratumNo1-Regular.eot",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/stratum/StratumNo1-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/stratum/StratumNo1-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/stratum/StratumNo1-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-stratumReg",
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={` ${urwdin.variable} ${stratum.variable} ${stratumReg.variable} antialiased`}
      >
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
